/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAppQuizRouteImport } from './routes/_authenticated/app.quiz'
import { Route as AuthenticatedAppPomodoroRouteImport } from './routes/_authenticated/app.pomodoro'
import { Route as AuthenticatedAppLeaderboardRouteImport } from './routes/_authenticated/app.leaderboard'
import { Route as AuthenticatedAppHistoryRouteImport } from './routes/_authenticated/app.history'
import { Route as AuthenticatedAppHighlightsRouteImport } from './routes/_authenticated/app.highlights'
import { Route as AuthenticatedAppFavoritesRouteImport } from './routes/_authenticated/app.favorites'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminUploadRouteImport } from './routes/_authenticated/admin/upload'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminRecoveryRouteImport } from './routes/_authenticated/admin/recovery'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated/admin/questions'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin/content'
import { Route as AuthenticatedAppYearYearIdRouteImport } from './routes/_authenticated/app.year.$yearId'
import { Route as AuthenticatedAppSubjectSubjectIdRouteImport } from './routes/_authenticated/app.subject.$subjectId'
import { Route as AuthenticatedAppResultAttemptIdRouteImport } from './routes/_authenticated/app.result.$attemptId'
import { Route as AuthenticatedAppModuleModuleIdRouteImport } from './routes/_authenticated/app.module.$moduleId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAppQuizRoute = AuthenticatedAppQuizRouteImport.update({
  id: '/app/quiz',
  path: '/app/quiz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPomodoroRoute =
  AuthenticatedAppPomodoroRouteImport.update({
    id: '/app/pomodoro',
    path: '/app/pomodoro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLeaderboardRoute =
  AuthenticatedAppLeaderboardRouteImport.update({
    id: '/app/leaderboard',
    path: '/app/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppHistoryRoute = AuthenticatedAppHistoryRouteImport.update({
  id: '/app/history',
  path: '/app/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppHighlightsRoute =
  AuthenticatedAppHighlightsRouteImport.update({
    id: '/app/highlights',
    path: '/app/highlights',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFavoritesRoute =
  AuthenticatedAppFavoritesRouteImport.update({
    id: '/app/favorites',
    path: '/app/favorites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUploadRoute =
  AuthenticatedAdminUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRecoveryRoute =
  AuthenticatedAdminRecoveryRouteImport.update({
    id: '/recovery',
    path: '/recovery',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppYearYearIdRoute =
  AuthenticatedAppYearYearIdRouteImport.update({
    id: '/app/year/$yearId',
    path: '/app/year/$yearId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSubjectSubjectIdRoute =
  AuthenticatedAppSubjectSubjectIdRouteImport.update({
    id: '/app/subject/$subjectId',
    path: '/app/subject/$subjectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppResultAttemptIdRoute =
  AuthenticatedAppResultAttemptIdRouteImport.update({
    id: '/app/result/$attemptId',
    path: '/app/result/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppModuleModuleIdRoute =
  AuthenticatedAppModuleModuleIdRouteImport.update({
    id: '/app/module/$moduleId',
    path: '/app/module/$moduleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/recovery': typeof AuthenticatedAdminRecoveryRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/upload': typeof AuthenticatedAdminUploadRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/favorites': typeof AuthenticatedAppFavoritesRoute
  '/app/highlights': typeof AuthenticatedAppHighlightsRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/app/pomodoro': typeof AuthenticatedAppPomodoroRoute
  '/app/quiz': typeof AuthenticatedAppQuizRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/module/$moduleId': typeof AuthenticatedAppModuleModuleIdRoute
  '/app/result/$attemptId': typeof AuthenticatedAppResultAttemptIdRoute
  '/app/subject/$subjectId': typeof AuthenticatedAppSubjectSubjectIdRoute
  '/app/year/$yearId': typeof AuthenticatedAppYearYearIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/recovery': typeof AuthenticatedAdminRecoveryRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/upload': typeof AuthenticatedAdminUploadRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/favorites': typeof AuthenticatedAppFavoritesRoute
  '/app/highlights': typeof AuthenticatedAppHighlightsRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/app/pomodoro': typeof AuthenticatedAppPomodoroRoute
  '/app/quiz': typeof AuthenticatedAppQuizRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/module/$moduleId': typeof AuthenticatedAppModuleModuleIdRoute
  '/app/result/$attemptId': typeof AuthenticatedAppResultAttemptIdRoute
  '/app/subject/$subjectId': typeof AuthenticatedAppSubjectSubjectIdRoute
  '/app/year/$yearId': typeof AuthenticatedAppYearYearIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/_authenticated/admin/recovery': typeof AuthenticatedAdminRecoveryRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/upload': typeof AuthenticatedAdminUploadRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/app/favorites': typeof AuthenticatedAppFavoritesRoute
  '/_authenticated/app/highlights': typeof AuthenticatedAppHighlightsRoute
  '/_authenticated/app/history': typeof AuthenticatedAppHistoryRoute
  '/_authenticated/app/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/_authenticated/app/pomodoro': typeof AuthenticatedAppPomodoroRoute
  '/_authenticated/app/quiz': typeof AuthenticatedAppQuizRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/module/$moduleId': typeof AuthenticatedAppModuleModuleIdRoute
  '/_authenticated/app/result/$attemptId': typeof AuthenticatedAppResultAttemptIdRoute
  '/_authenticated/app/subject/$subjectId': typeof AuthenticatedAppSubjectSubjectIdRoute
  '/_authenticated/app/year/$yearId': typeof AuthenticatedAppYearYearIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin/content'
    | '/admin/questions'
    | '/admin/recovery'
    | '/admin/settings'
    | '/admin/upload'
    | '/admin/users'
    | '/app/favorites'
    | '/app/highlights'
    | '/app/history'
    | '/app/leaderboard'
    | '/app/pomodoro'
    | '/app/quiz'
    | '/admin/'
    | '/app/'
    | '/app/module/$moduleId'
    | '/app/result/$attemptId'
    | '/app/subject/$subjectId'
    | '/app/year/$yearId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/content'
    | '/admin/questions'
    | '/admin/recovery'
    | '/admin/settings'
    | '/admin/upload'
    | '/admin/users'
    | '/app/favorites'
    | '/app/highlights'
    | '/app/history'
    | '/app/leaderboard'
    | '/app/pomodoro'
    | '/app/quiz'
    | '/admin'
    | '/app'
    | '/app/module/$moduleId'
    | '/app/result/$attemptId'
    | '/app/subject/$subjectId'
    | '/app/year/$yearId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/questions'
    | '/_authenticated/admin/recovery'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/upload'
    | '/_authenticated/admin/users'
    | '/_authenticated/app/favorites'
    | '/_authenticated/app/highlights'
    | '/_authenticated/app/history'
    | '/_authenticated/app/leaderboard'
    | '/_authenticated/app/pomodoro'
    | '/_authenticated/app/quiz'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/app/module/$moduleId'
    | '/_authenticated/app/result/$attemptId'
    | '/_authenticated/app/subject/$subjectId'
    | '/_authenticated/app/year/$yearId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/app/quiz': {
      id: '/_authenticated/app/quiz'
      path: '/app/quiz'
      fullPath: '/app/quiz'
      preLoaderRoute: typeof AuthenticatedAppQuizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/pomodoro': {
      id: '/_authenticated/app/pomodoro'
      path: '/app/pomodoro'
      fullPath: '/app/pomodoro'
      preLoaderRoute: typeof AuthenticatedAppPomodoroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/leaderboard': {
      id: '/_authenticated/app/leaderboard'
      path: '/app/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AuthenticatedAppLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/history': {
      id: '/_authenticated/app/history'
      path: '/app/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AuthenticatedAppHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/highlights': {
      id: '/_authenticated/app/highlights'
      path: '/app/highlights'
      fullPath: '/app/highlights'
      preLoaderRoute: typeof AuthenticatedAppHighlightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/favorites': {
      id: '/_authenticated/app/favorites'
      path: '/app/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AuthenticatedAppFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/upload': {
      id: '/_authenticated/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AuthenticatedAdminUploadRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/recovery': {
      id: '/_authenticated/admin/recovery'
      path: '/recovery'
      fullPath: '/admin/recovery'
      preLoaderRoute: typeof AuthenticatedAdminRecoveryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/app/year/$yearId': {
      id: '/_authenticated/app/year/$yearId'
      path: '/app/year/$yearId'
      fullPath: '/app/year/$yearId'
      preLoaderRoute: typeof AuthenticatedAppYearYearIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/subject/$subjectId': {
      id: '/_authenticated/app/subject/$subjectId'
      path: '/app/subject/$subjectId'
      fullPath: '/app/subject/$subjectId'
      preLoaderRoute: typeof AuthenticatedAppSubjectSubjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/result/$attemptId': {
      id: '/_authenticated/app/result/$attemptId'
      path: '/app/result/$attemptId'
      fullPath: '/app/result/$attemptId'
      preLoaderRoute: typeof AuthenticatedAppResultAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/module/$moduleId': {
      id: '/_authenticated/app/module/$moduleId'
      path: '/app/module/$moduleId'
      fullPath: '/app/module/$moduleId'
      preLoaderRoute: typeof AuthenticatedAppModuleModuleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
  AuthenticatedAdminRecoveryRoute: typeof AuthenticatedAdminRecoveryRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUploadRoute: typeof AuthenticatedAdminUploadRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
    AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
    AuthenticatedAdminRecoveryRoute: AuthenticatedAdminRecoveryRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminUploadRoute: AuthenticatedAdminUploadRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAppFavoritesRoute: typeof AuthenticatedAppFavoritesRoute
  AuthenticatedAppHighlightsRoute: typeof AuthenticatedAppHighlightsRoute
  AuthenticatedAppHistoryRoute: typeof AuthenticatedAppHistoryRoute
  AuthenticatedAppLeaderboardRoute: typeof AuthenticatedAppLeaderboardRoute
  AuthenticatedAppPomodoroRoute: typeof AuthenticatedAppPomodoroRoute
  AuthenticatedAppQuizRoute: typeof AuthenticatedAppQuizRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppModuleModuleIdRoute: typeof AuthenticatedAppModuleModuleIdRoute
  AuthenticatedAppResultAttemptIdRoute: typeof AuthenticatedAppResultAttemptIdRoute
  AuthenticatedAppSubjectSubjectIdRoute: typeof AuthenticatedAppSubjectSubjectIdRoute
  AuthenticatedAppYearYearIdRoute: typeof AuthenticatedAppYearYearIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAppFavoritesRoute: AuthenticatedAppFavoritesRoute,
  AuthenticatedAppHighlightsRoute: AuthenticatedAppHighlightsRoute,
  AuthenticatedAppHistoryRoute: AuthenticatedAppHistoryRoute,
  AuthenticatedAppLeaderboardRoute: AuthenticatedAppLeaderboardRoute,
  AuthenticatedAppPomodoroRoute: AuthenticatedAppPomodoroRoute,
  AuthenticatedAppQuizRoute: AuthenticatedAppQuizRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppModuleModuleIdRoute: AuthenticatedAppModuleModuleIdRoute,
  AuthenticatedAppResultAttemptIdRoute: AuthenticatedAppResultAttemptIdRoute,
  AuthenticatedAppSubjectSubjectIdRoute: AuthenticatedAppSubjectSubjectIdRoute,
  AuthenticatedAppYearYearIdRoute: AuthenticatedAppYearYearIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
